### ISSUE TITLE
[BUG] Fix website title icon and text

### ISSUE THREAD

**Issue by rezwancs** [rezwan2525/flashcard-react#1]
**Describe the bug**
Currently, the title of the website is default "React App" and "ReactJs" icon. 

**To Reproduce**
1. Go to the website
2. Observe the title of the website

**Expected behavior**
* The title should be "React Flashcard App"
* The title icon should be same as the navbar

**Screenshots**
![image](https://user-images.githubusercontent.com/30120066/194741442-1781ff38-1190-465c-b1cc-a1f2a8c4c39a.png)

**Comment by trishitchar** [comment]
@rezwan2525
Hey! Can I work on this issue.

**Comment by rezwancs** [comment]
@trishitchar Yes sure, please go ahead.🤩

**Comment by rezwancs** [comment]
@trishitchar This issue was resolved in this PR  https://github.com/rezwan2525/flashcard-react/pull/5 , but the icon is not updated yet. Since it's already assigned to you, could you please work on it?
