### ISSUE TITLE
[FEATURE] Add link to documentation 

### ISSUE THREAD

**Issue by Snehil0603** [rezwan2525/flashcard-react#19]
We can add link to documentation for particular topic

**Comment by rezwancs** [comment]
@Snehil0603 Could you please give us some example ?

**Comment by Snehil0603** [comment]
## Like for Components link to ` https://reactjs.org/docs/components-and-props.html` can be added to the place highlighted below
![ll](https://user-images.githubusercontent.com/96441611/194928212-9976f4a5-cc61-43bc-8c8d-419a542ede50.jpg)

**Comment by rezwancs** [comment]
Actually, it's not aligned with the current purpose of this project.
