### ISSUE TITLE
[BUG] Button design improvement

### ISSUE THREAD

**Issue by rezwancs** [rezwan2525/flashcard-react#2]
**Describe the bug**
Similar type buttons "Prev" and "Next" should have similar text colors to keep the design consistent.

**To Reproduce**
1. Go to the website
2. Observe the "Prev" and "Next" button

**Expected behavior**
* The "Prev" and "Next" both button's text color should be "white".

**Screenshots**
![image](https://user-images.githubusercontent.com/30120066/194741538-e2c313fe-dc08-4659-b9c3-80256335e6df.png)

**Comment by Nevilkumar** [comment]
Hi @rezwan2525 I would like to work on this issue. Can you please assign it to me?

**Comment by trishitchar** [comment]
![image](https://user-images.githubusercontent.com/90543153/194741934-ef0cb13b-1442-4bc5-be52-749f55ffcc35.png)

**Comment by trishitchar** [comment]
I can fix this

**Comment by rezwancs** [comment]
@Nevilkumar Yes sure, please go ahead.🤩
