### ISSUE TITLE
[FEATURE] Convert application to Progressive web application

### ISSUE THREAD

**Issue by t-bello7** [rezwan2525/flashcard-react#27]
**Is your feature request related to a problem? Please describe.**
To avoid users always open up the browser and then look for your website. Making the application a progressive web application would give users the ability to add to the home screen of their device. This is would give a one-click web experience to the application

**Describe the solution you'd like**
Implementing a PWA means the application has to pass the minimum performance required for a PWA.

**Comment by t-bello7** [comment]
I would like to work on this issue as an hacktoberfest contributor

**Comment by rezwancs** [comment]
@t-bello7 Yes sure, please go ahead.🤩
