### ISSUE TITLE
[FEATURE] Store `flashcard` contents to local storage

### ISSUE THREAD

**Issue by rezwancs** [rezwan2525/flashcard-react#7]
**Is your feature request related to a problem? Please describe.**
Currently, we show static `flashcards` contents, stored in 'datasource.js' file.

**Describe the solution you'd like**
We should store flashcard contents in local storage and access them from local storage.

**Required knowledge:**
* localStorage
* React Hook

**Comment by whyang0808** [comment]
Hi, could you assign this task to me?

**Comment by rezwancs** [comment]
@whyang0808  Yes sure, please go ahead.🤩
